"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-20 10:18:12.946843
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mailbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailbox_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_mailbox_external_id'), ['external_id'], unique=False)

    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_is_used'), ['is_used'], unique=False)

    op.create_table('webhook_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_status'), ['status'], unique=False)
        batch_op.create_index('ix_webhook_queue', ['status', 'next_attempt_at'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('thread_key', sa.String(length=255), nullable=True),
    sa.Column('mailbox_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_external_id'), ['external_id'], unique=False)
        batch_op.create_index('ix_message_mailbox_id_id', ['mailbox_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_message_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index('ix_message_outbox', ['direction', 'status', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_thread_key'), ['thread_key'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id_fk', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id_fk'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_message_id_fk'), ['message_id_fk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_message_id_fk'))

    op.drop_table('attachment')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_thread_key'))
        batch_op.drop_index(batch_op.f('ix_message_status'))
        batch_op.drop_index(batch_op.f('ix_message_recipient'))
        batch_op.drop_index('ix_message_outbox')
        batch_op.drop_index(batch_op.f('ix_message_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_message_message_id'))
        batch_op.drop_index('ix_message_mailbox_id_id')
        batch_op.drop_index(batch_op.f('ix_message_external_id'))
        batch_op.drop_index(batch_op.f('ix_message_direction'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_index('ix_webhook_queue')
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_next_attempt_at'))

    op.drop_table('webhook_delivery')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_is_used'))
        batch_op.drop_index(batch_op.f('ix_upload_created_at'))

    op.drop_table('upload')
    with op.batch_alter_table('mailbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailbox_external_id'))
        batch_op.drop_index(batch_op.f('ix_mailbox_address'))

    op.drop_table('mailbox')
    # ### end Alembic commands ###
